namespace HotMic.Core.Presets;

internal static partial class BuiltInPresetCatalog
{
    private static PluginPresetBank BuildVocalSpectrographBank()
    {
        var baseParameters = new Dictionary<string, float>(StringComparer.OrdinalIgnoreCase)
        {
            ["FFT Size"] = 2048f,
            ["Window"] = (float)WindowFunction.Hann,
            ["Overlap"] = 0.75f,
            ["Scale"] = (float)FrequencyScale.Mel,
            ["Min Freq"] = 80f,
            ["Max Freq"] = 8000f,
            ["Min dB"] = -80f,
            ["Max dB"] = 0f,
            ["Time Window"] = 5f,
            ["Color Map"] = 6f,
            ["Pitch Overlay"] = 1f,
            ["Formants"] = 1f,
            ["Harmonics"] = 1f,
            ["Voicing"] = 1f,
            ["Pre-Emphasis"] = 1f,
            ["HPF Enabled"] = 1f,
            ["HPF Cutoff"] = 60f,
            ["LPC Order"] = 12f,
            ["Reassign"] = (float)SpectrogramReassignMode.Off,
            ["Reassign Threshold"] = -60f,
            ["Reassign Spread"] = 1f,
            ["Clarity Mode"] = (float)ClarityProcessingMode.Full,
            ["Clarity Noise"] = 1f,
            ["Clarity Harmonic"] = 1f,
            ["Clarity Smoothing"] = 0.3f,
            ["Pitch Algorithm"] = (float)PitchDetectorType.Yin,
            ["Axis Mode"] = (float)SpectrogramAxisMode.Hz,
            ["Voice Range"] = (float)VocalRangeType.Tenor,
            ["Range Overlay"] = 1f,
            ["Guides"] = 1f,
            ["Waveform View"] = 1f,
            ["Spectrum View"] = 1f,
            ["Pitch Meter"] = 1f,
            ["Vowel View"] = 1f,
            ["Smoothing Mode"] = (float)SpectrogramSmoothingMode.Ema,
            ["Brightness"] = 1f,
            ["Gamma"] = 0.8f,
            ["Contrast"] = 1.2f,
            ["Color Levels"] = 32f,
            ["Normalization"] = (float)SpectrogramNormalizationMode.None,
            ["Dynamic Range"] = (float)SpectrogramDynamicRangeMode.Custom
        };

        PluginPreset CreateVocalPreset(string name, params (string parameter, float value)[] overrides)
        {
            var parameters = new Dictionary<string, float>(baseParameters, StringComparer.OrdinalIgnoreCase);
            for (int i = 0; i < overrides.Length; i++)
            {
                parameters[overrides[i].parameter] = overrides[i].value;
            }
            return new PluginPreset(name, parameters);
        }

        return new PluginPresetBank("builtin:vocal-spectrograph",
        [
            CreateVocalPreset("SpeechMale",
                ("Voice Range", (float)VocalRangeType.Baritone),
                ("Min Freq", 60f),
                ("Time Window", 6f),
                ("Clarity Noise", 0.8f),
                ("Clarity Harmonic", 0.8f)),
            CreateVocalPreset("SpeechFemale",
                ("Voice Range", (float)VocalRangeType.Alto),
                ("Min Freq", 100f),
                ("Max Freq", 9000f),
                ("Time Window", 6f),
                ("Clarity Noise", 0.8f),
                ("Clarity Harmonic", 0.8f)),
            CreateVocalPreset("SingingClassical",
                ("FFT Size", 4096f),
                ("Window", (float)WindowFunction.BlackmanHarris),
                ("Overlap", 0.875f),
                ("Scale", (float)FrequencyScale.Logarithmic),
                ("Min Freq", 60f),
                ("Max Freq", 10000f),
                ("Min dB", -80f),
                ("Time Window", 8f),
                ("Reassign", (float)SpectrogramReassignMode.Frequency),
                ("Clarity Smoothing", 0.35f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Bilateral),
                ("Brightness", 1.1f),
                ("Gamma", 0.75f),
                ("Contrast", 1.25f)),
            CreateVocalPreset("SingingContemporary",
                ("Max Freq", 12000f),
                ("Time Window", 6f),
                ("Color Map", 1f),
                ("Voice Range", (float)VocalRangeType.MezzoSoprano),
                ("Clarity Noise", 0.9f),
                ("Clarity Harmonic", 0.9f),
                ("Brightness", 1.15f),
                ("Gamma", 0.78f),
                ("Contrast", 1.3f)),
            CreateVocalPreset("VoiceoverAnalysis",
                ("FFT Size", 4096f),
                ("Window", (float)WindowFunction.BlackmanHarris),
                ("Overlap", 0.875f),
                ("Min Freq", 70f),
                ("Max Freq", 9000f),
                ("Min dB", -65f),
                ("Time Window", 6f),
                ("Reassign", (float)SpectrogramReassignMode.Frequency),
                ("Clarity Smoothing", 0.35f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Bilateral),
                ("Gamma", 0.75f),
                ("Contrast", 1.25f)),
            CreateVocalPreset("PitchTracking",
                ("FFT Size", 1024f),
                ("Overlap", 0.875f),
                ("Scale", (float)FrequencyScale.Logarithmic),
                ("Time Window", 4f),
                ("Formants", 0f),
                ("Harmonics", 0f),
                ("Vowel View", 0f),
                ("Clarity Mode", (float)ClarityProcessingMode.Noise),
                ("Clarity Noise", 0.6f),
                ("Clarity Harmonic", 0f),
                ("Clarity Smoothing", 0.2f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Ema)),
            CreateVocalPreset("FormantAnalysis",
                ("Window", (float)WindowFunction.Gaussian),
                ("Min dB", -75f),
                ("Pitch Overlay", 0f),
                ("Harmonics", 0f),
                ("LPC Order", 16f),
                ("Clarity Noise", 0.8f),
                ("Clarity Harmonic", 0.6f),
                ("Clarity Smoothing", 0.25f)),
            CreateVocalPreset("HarmonicDetail",
                ("FFT Size", 4096f),
                ("Window", (float)WindowFunction.BlackmanHarris),
                ("Overlap", 0.875f),
                ("Scale", (float)FrequencyScale.Logarithmic),
                ("Min dB", -75f),
                ("Formants", 0f),
                ("Reassign", (float)SpectrogramReassignMode.Frequency),
                ("Clarity Noise", 0.8f),
                ("Clarity Harmonic", 1f),
                ("Clarity Smoothing", 0.35f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Bilateral),
                ("Time Window", 6f)),
            CreateVocalPreset("TransientCapture",
                ("FFT Size", 1024f),
                ("Overlap", 0.5f),
                ("Scale", (float)FrequencyScale.Linear),
                ("Time Window", 3f),
                ("Min dB", -60f),
                ("Pitch Overlay", 0f),
                ("Formants", 0f),
                ("Harmonics", 0f),
                ("Voicing", 0f),
                ("Pitch Meter", 0f),
                ("Vowel View", 0f),
                ("Clarity Mode", (float)ClarityProcessingMode.Noise),
                ("Clarity Noise", 0.4f),
                ("Clarity Harmonic", 0f),
                ("Clarity Smoothing", 0f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Off)),
            CreateVocalPreset("Presentation",
                ("Time Window", 10f),
                ("Axis Mode", (float)SpectrogramAxisMode.Both),
                ("Brightness", 1.2f),
                ("Gamma", 0.75f),
                ("Contrast", 1.35f),
                ("Color Levels", 24f),
                ("Clarity Smoothing", 0.35f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Bilateral)),
            CreateVocalPreset("Technical",
                ("Min dB", -90f),
                ("Axis Mode", (float)SpectrogramAxisMode.Both),
                ("Clarity Mode", (float)ClarityProcessingMode.None),
                ("Clarity Noise", 0f),
                ("Clarity Harmonic", 0f),
                ("Clarity Smoothing", 0f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Off),
                ("Brightness", 1f),
                ("Gamma", 1f),
                ("Contrast", 1f),
                ("Color Levels", 64f)),
            CreateVocalPreset("Minimal",
                ("Time Window", 8f),
                ("Pitch Overlay", 0f),
                ("Formants", 0f),
                ("Harmonics", 0f),
                ("Voicing", 0f),
                ("Range Overlay", 0f),
                ("Guides", 0f),
                ("Waveform View", 0f),
                ("Spectrum View", 0f),
                ("Pitch Meter", 0f),
                ("Vowel View", 0f)),
            CreateVocalPreset("Maximum Clarity",
                ("Min dB", -65f),
                ("Clarity Mode", (float)ClarityProcessingMode.Full),
                ("Clarity Noise", 1f),
                ("Clarity Harmonic", 1f),
                ("Clarity Smoothing", 0.35f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Bilateral),
                ("Gamma", 0.75f)),
            CreateVocalPreset("Balanced"),
            CreateVocalPreset("Low Latency",
                ("FFT Size", 1024f),
                ("Overlap", 0.5f),
                ("Min dB", -60f),
                ("Clarity Mode", (float)ClarityProcessingMode.Noise),
                ("Clarity Noise", 0.5f),
                ("Clarity Harmonic", 0f),
                ("Clarity Smoothing", 0.2f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Ema),
                ("Gamma", 0.85f)),
            CreateVocalPreset("Analysis Mode",
                ("Min dB", -80f),
                ("Clarity Mode", (float)ClarityProcessingMode.None),
                ("Clarity Noise", 0f),
                ("Clarity Harmonic", 0f),
                ("Clarity Smoothing", 0f),
                ("Smoothing Mode", (float)SpectrogramSmoothingMode.Off),
                ("Gamma", 1f),
                ("Contrast", 1f),
                ("Brightness", 1f))
        ]);
    }
}
